### ISSUE TITLE
Problem with timing of get_serializer() in new update

### ISSUE THREAD

**Issue by camgnostic** [InterSIS/django-rest-encrypted-lookup#8]
I'm getting repeated issues with get_serializer() in dispatch() causing a chain of errors (no self.request, no self.format_kwarg, etc) with the switch from a generic id_cipher import to a call from the serializer.  My current problem-solve is attached as a pull-request, but I don't think that's the solution.  Perhaps making get_cipher a class method?  I'm not sure where this project is heading insofar as encrypting strings specific to model / instance, so I don't know what the solution is.

**Comment by JASchilz** [comment]
Let's talk Saturday.

**Comment by JASchilz** [comment]
Issue resolved.
